### **NUMPY**

In [1]:
import numpy as np

**Create Array**

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


**Checking NumPy Version**

In [3]:
print(np.__version__)

1.22.4


In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


**1-D Arrays**

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


**2-D Arrays** 

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


**3-D Arrays** 

In [8]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Check Number of Dimensions**

In [9]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


**Create an array with n dimensions**

In [10]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [11]:
print('number of dimensions :', arr.ndim)

number of dimensions : 5


**Access Array Elements**

In [12]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


**Negative Indexing**

In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


**Slicing arrays**

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


**Negative Slicing**

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


**Step**

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


**Slicing 2-D Arrays**

In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


**From both elements, slice index 1 to index 4 (not included), this will return 2-D array:**

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**Checking the Data Type of an Array**

In [38]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


**Shape of an Array**

In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


**Reshape**

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 2)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (4,2)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**NumPy Array Iterating**

In [27]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**Iterating Arrays Using nditer()**

In [29]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**Joining**

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [43]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2))
print(arr)
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [44]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [46]:
np.delete(arr, [1,3,5], None)

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])

**Splitting NumPy Arrays**

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [47]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


**Sorting**

In [36]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]
